# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Arox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for Arox
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'FBSDKCoreKit', '4.17.0'
  pod 'FBSDKLoginKit', '4.17.0'
  pod 'SDWebImage', '~> 4.0'
pod 'SVProgressHUD'


 
  target 'AroxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AroxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
